// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/test/main.go

// Package main is a generated GoMock package.
package main

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPeopleRepositoryInterface is a mock of PeopleRepositoryInterface interface.
type MockPeopleRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPeopleRepositoryInterfaceMockRecorder
}

// MockPeopleRepositoryInterfaceMockRecorder is the mock recorder for MockPeopleRepositoryInterface.
type MockPeopleRepositoryInterfaceMockRecorder struct {
	mock *MockPeopleRepositoryInterface
}

// NewMockPeopleRepositoryInterface creates a new mock instance.
func NewMockPeopleRepositoryInterface(ctrl *gomock.Controller) *MockPeopleRepositoryInterface {
	mock := &MockPeopleRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPeopleRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeopleRepositoryInterface) EXPECT() *MockPeopleRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetAllPeople mocks base method.
func (m *MockPeopleRepositoryInterface) GetAllPeople() []Person {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPeople")
	ret0, _ := ret[0].([]Person)
	return ret0
}

// GetAllPeople indicates an expected call of GetAllPeople.
func (mr *MockPeopleRepositoryInterfaceMockRecorder) GetAllPeople() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPeople", reflect.TypeOf((*MockPeopleRepositoryInterface)(nil).GetAllPeople))
}

// GetPersonByName mocks base method.
func (m *MockPeopleRepositoryInterface) GetPersonByName(name string) Person {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersonByName", name)
	ret0, _ := ret[0].(Person)
	return ret0
}

// GetPersonByName indicates an expected call of GetPersonByName.
func (mr *MockPeopleRepositoryInterfaceMockRecorder) GetPersonByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersonByName", reflect.TypeOf((*MockPeopleRepositoryInterface)(nil).GetPersonByName), name)
}
